apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 2 
  selector:
    matchExpressions:
    - key: env
      operator: In
      values:
      - dev 
  template: 
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
